[config]
debug = true  # 除錯模式

[alarm]
print = true                        # 印出警告訊息
windows_sound = true                # 播放Windows警告音效
tts_enable = true                   # 是否啟用文字轉語音
tts_host = "http://127.0.0.1:9880/" # 文字轉語音伺服器
device = "CABLE Input"              # 輸出裝置
sovits_path = "your_sovits_model.pth"  # SoVITS模型路徑
gpt_path = "your_gpt_model.ckpt"     # GPT模型路徑
ref_wav_path = "your_wav_file.wav"   # 參考音頻路徑
prompt_text = "Your prompt text."    # 提示文字
prompt_language = "zh"               # 提示文字語言
text_language = "中英混合"            # 文字語言

[detect_crosswalk_signal]
invalid_time = 3  # 無效時間(秒)

[obstacle_detection]
my_height = 180                     # 身高
camera_height = 100                 # 攝影機高度
lowest_obstacle_height = 5          # 最低障礙物高度
highest_hole_height = -10           # 最高坑洞高度
lateral_distance_threshold = 500    # 橫向距離閥值
missing_point_alarm = false         # 缺失點警告
missing_point_threshold = 10        # 缺失點閥值
missing_point_alarm_interval = 0.3  # 缺失點警告間隔
# 檢測區域
area = [
    [0, 0],
    [0, 720],
    [1280, 720],
    [1280, 0]
]
# 坑洞距離警告配置
hole_preset = [
    { distance = 500, interval = 0.3, name = "近距離" },
    { distance = 1000, interval = 0.6, name = "中距離" },
    { distance = 1500, interval = 1.0, name = "遠距離" },
]
# 障礙物警告距離警告配置
obstacle_preset = [
    { distance = 500, interval = 0.3, name = "近距離" },
    { distance = 750, interval = 0.6, name = "中距離" },
    { distance = 1000, interval = 1.0, name = "遠距離" },
]

[detect_object]
max_distance_threshold = 5000       # 最大距離閥值（mm）
lateral_distance_threshold = 500    # 橫向距離閥值（mm）

[realsense]
depth_min = 0.11  # 深度攝影機最近深度距離
depth_max = 1.0   # 深度攝影機最遠深度距離

[yolo]
confidence_threshold = 0.7        # 置信度閥值
model = "models/yolov8n.pt"       # YOLO官方模型
cs_model = "models/best.pt"       # 行人號誌模型

[sahi]
slice_height = 256
slice_width = 256
overlap_height_ratio = 0.2
overlap_width_ratio = 0.2
