[config]
debug = true # 除錯模式
image = "resource/images.jpg"
video = "resource/行人輔助交通號誌.mp4"
skip_frame = 10  # 跳過幾幀

[alarm]
print = true          # 印出警告訊息
windows_sound = true  # 播放Windows警告音效

[detect_crosswalk_signal]
invalid_time = 3  # 無效時間(秒)

[realsense]
depth_min = 0.11  # 深度攝影機最近深度距離
depth_max = 1.0   # 深度攝影機最遠深度距離

[yolo]
confidence_threshold = 0.3        # 置信度閥值
model = "models/yolov8n.pt"       # YOLO官方模型
cs_model = "models/best.pt"       # 行人號誌模型

[sahi]
slice_height = 256
slice_width = 256
overlap_height_ratio = 0.2
overlap_width_ratio = 0.2